### ISSUE TITLE
Quero teu contatoooo!!

### ISSUE THREAD

**Issue by jonatasfreitasv** [MrLucasCardoso/pyzenvia#1]
Fala meu tudo bem?

Sou Jonatas Freitas, dev da Zenvia, gostei do teu pacote e gostaria de fazer algumas atualizações e publicar na página oficial da Zenvia, me manda uma mensagem para conversarmos, abraços!

jonatas.freitas@zenvia.com.

**Comment by mrlucascardoso** [comment]
Opa tudo bem sim, fico bastante grato por isso, meus contatos são:
Email: mr.lucascardoso@gmail.com
Telefone/Whatsapp: 86 99918-1896
Facebook: https://www.facebook.com/mr.lucascardoso

**Comment by mrlucascardoso** [comment]
Te adicionei como colaborador, aceita lá !

**Comment by jonatasfreitasv** [comment]
Massa meu! Fiz um fork e mandei pra página da http://zenvia.github.io, vlw!!!
